date: 2025-06-02
title: Create a model-driven application in Power Apps
file: /img/training/create-app-models-business-processes.svg
link: https://learn.microsoft.com/api/achievements/share/en-us/NicolasdeMontigny-3735/URV58VD3?sharingId=E4C528F082174B55