date: 2025-06-02
title: Create and manage model-driven apps with Power Apps and Dataverse
file: /img/training/generic-trophy.svg
link: https://learn.microsoft.com/api/achievements/share/en-us/NicolasdeMontigny-3735/QSC74WVE?sharingId=E4C528F082174B55