#!/bin/sh

# Python virtual environment
python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt

# Instantiate project
sphinx-quickstart --ext-githubpages
# > Separate source and build directories (y/n) [n]: y
# > Project name: portfolio
# > Author name(s): Nicolas de Montigny
# > Project release []: 2.0
# > Project language [en]: en

# Build project
sphinx-build -M html source build
# Use the Makefile to build the docs, like so:
# where "builder" is one of the supported builders, e.g. html, latex or linkcheck.