# This file was created automatically with `myst init --gh-pages` 🪄 💚

name: Deploy to GitHub Pages
on:
  pull_request:
  push:
    # Runs on pushes targeting the default branch
    branches: 
    - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Pages
      uses: actions/configure-pages@v5

    # Setup Node.js + dependencies
    - uses: actions/setup-node@v4
      with:
        node-version: '18.19.1'

    - name: Install MyST
      run: npm install -g mystmd

    # Setup Python + dependencies
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'
    
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv pip install --system -r requirements.txt

    # Build the site
    - name: Build the site
      run: |
        myst build --html
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: './_build/html'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
