# This file was created automatically with `myst init --gh-pages` 🪄 💚

name: Deploy to GitHub Pages
on:
  pull_request:
  push:
    # Runs on pushes targeting the default branch
    branches: 
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'
    
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv pip install --system -r requirements.txt
        uv pip install --system -r execute-requirements.txt

    # Build the book
    - name: Build the site
      run: |
        myst build --html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    # If we've pushed to main, push the book's HTML to github-pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html